author           = InnovAnon
depends          = default,airtanks,ia_util,tidesandfloods
description      = A place
name             = ia_space
optional_depends = ia_thermal
title            = IA Outer Space

