author           = InnovAnon
depends          = airtanks, default, ia_util, player_monoids
description      = A place
name             = ia_space
optional_depends = regional_weather, tides, tidesandfloods, radiant_damage
title            = IA Outer Space

